--[[
    > ran by luve <3
    > runtime: 1626ms
]]
print("anti env by za1k <3")
local CorePackages = game:GetService("CorePackages")
local CorePackages = game:GetService("CorePackages")
local RunService = game:GetService("RunService")
local RunService = game:GetService("RunService")
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
RunService:IsStudio()
require("@lune/fs")
local Players = game:GetService("Players")
Players:GetPlayers()
for k, v in ipairs({table: 0x309ea82368b1edf8}) do
LocalPlayer:IsA("Player")
end -- ipairs
local VoiceChatService = game:GetService("VoiceChatService")
local VoiceChatService = game:GetService("VoiceChatService")
print("straight BALL knowledge if ur getting this far")
local SoundService = game:GetService("SoundService")
local SoundService = game:GetService("SoundService")
local AssetService = game:GetService("AssetService")
local AssetService = game:GetService("AssetService")
cloneref()
AssetService:CreateEditableMesh()
Vector3.new(43.39769637923974, 45.113483801570304, 39.105135179554665)
AssetService:AddVertex(43.39769744873047, 45.11348342895508, 39.10513687133789)
Vector3.new(1, 1, 1)
AssetService:AddVertex(1, 1, 1)
Vector3.new(2, 2, 2)
AssetService:AddVertex(2, 2, 2)
Vector3.new(3, 3, 3)
AssetService:AddVertex(3, 3, 3)
Vector3.new(4, 4, 4)
AssetService:AddVertex(4, 4, 4)
Vector3.new(5, 5, 5)
AssetService:AddVertex(5, 5, 5)
AssetService:GetPosition(1)
AssetService:Destroy()
local Debris = game:GetService("Debris")
local Debris = game:GetService("Debris")
Instance.new("Part")
Debris:AddItem(Part, 0.1)
local HttpService = game:GetService("HttpService")
local HttpService = game:GetService("HttpService")
HttpService:GenerateGUID()
HttpService:GenerateGUID()
local UserInputService = game:GetService("UserInputService")
local UserInputService = game:GetService("UserInputService")
UserInputService:GetMouseLocation()
Instance.new("Part")
print("You are ud @za1k with your result including me n shit!")